### PR TITLE
fix clion-bundled-jdk sha & update conflicts_with.

### PR DESCRIPTION
**Pull request by andystanton**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Pinging @sebroeder.

**Comment by sebroeder** [comment]
@andystanton good catch regarding the SHA1 mismatch, I could reproduce this on my system. Could you please revert the change go the `conflicts_with` stanza please? This cask only conflicts with `clion` since you can install CLion and CLion EAP next to each other.

@vitorgalvao Doesn't the travis build check for SHA1 mismatches?

**Comment by vitorgalvao** [comment]
`sha256` you mean, but no, it doesn’t. That’d require downloading every file, and that’d take a lot of bandwidth. Travis checks for correctness in the cask itself, not in the results.

**Comment by jawshooah** [comment]
It's for Travis to determine which Casks were added or changed by a PR and
verify only those hashes.

**Comment by vitorgalvao** [comment]
I didn’t mean every time, if that’s what you mean, but that’s still a lot of bandwidth. I haven’t used Travis much so I don’t have a strong opinion either way, but even if we could do it for free I'm not sure I’d be comfortable with it (maybe we’re even supposed to, and that’s OK, but for such a trivial matter, not sure it’s worth it).

**Comment by jawshooah** [comment]
In any case, this is way off-topic. I'll open a thread on the main repo for further discussion.

**Comment by andystanton** [comment]
I'm closing this PR as 1.0.5 is out anyway and the ```conflicts_with``` stanza change was incorrect.

A fresh PR for 1.0.5 will be a bit cleaner.

**Pull request closed without merging**
