### PR TITLE
Updated version of atom-beta version to latest (1.6.0-beta0)

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by adidalal** [comment]
```
diff --git a/Casks/atom-beta.rb b/Casks/atom-beta.rb
index bb86576..f1cef1d 100644
--- a/Casks/atom-beta.rb
+++ b/Casks/atom-beta.rb
@@ -1,11 +1,11 @@
 cask 'atom-beta' do
-  version '1.5.0-beta3'
-  sha256 'f6302ce5b505e4186d7a0fee41690868eab0dee038bf9926d973c3d1766fb70d'
+  version '1.6.0-beta0'
+  sha256 '2ac599628d8a247a3f247732dc01af251d70caf9405e62f871db349ee75189e0'
 
   # github.com is the official download host per the vendor homepage
   url "https://github.com/atom/atom/releases/download/v#{version}/atom-mac.zip"
   appcast 'https://github.com/atom/atom/releases.atom',
-          checkpoint: '8e5c44d6f35060f74bf352ef898fea7c394fea554ac1e89cf33bef3cc9624f1f'
+          checkpoint: '29776125d16234655b33d4238ab3f2279f5ae0ebd978afee7aeab4aa62f9d29f'
```

if needed.

I also suggest cask-repair, for ease of use, though.

**Comment by amilajack** [comment]
@adidalal how did you get the checksum? Couldnt get it to work

**Comment by adidalal** [comment]
Follow @vitorgalvao's instructions above.

You can close this PR, switch back to `master` and make a new one via cask-repair, if it's easier (probably is, honestly)

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

Follow the first 2 sections

**Comment by amilajack** [comment]
Got this:

```
➜  Casks git:(master) cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
➜  Casks git:(master) cask-repair --pull origin --push $github_user $outdated_cask
error: branch 'cask-repair_update-atom-beta' not found.

There is no such cask

➜  Casks git:(master)
```

**Comment by amilajack** [comment]
Fixed it. The ```CONTRIBUTING.md``` instructed me to:
``
cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks"
```
but the cask was a beta version, so what I was actually supposed to do was
```
cd "$(brew --repository)/Library/Taps/caskroom/homebrew-versions/Casks"
```
Here's the output:
```
Type the new version (or leave blank to abort)
> 1.6.0-beta0
==> Downloading external files for Cask ./atom-beta.rb
==> Downloading https://github.com/atom/atom/releases/download/v1.6.0-beta0/atom-mac.zip
######################################################################## 100.0%
==> No checksum defined for Cask atom-beta, skipping verification
==> Success! Downloaded to -> /Library/Caches/Homebrew/atom-beta-1.6.0-beta0.zip
diff --git a/Casks/atom-beta.rb b/Casks/atom-beta.rb
index bb86576..f1cef1d 100644
--- a/Casks/atom-beta.rb
+++ b/Casks/atom-beta.rb
@@ -1,11 +1,11 @@
 cask 'atom-beta' do
-  version '1.5.0-beta3'
-  sha256 'f6302ce5b505e4186d7a0fee41690868eab0dee038bf9926d973c3d1766fb70d'
+  version '1.6.0-beta0'
+  sha256 '2ac599628d8a247a3f247732dc01af251d70caf9405e62f871db349ee75189e0'

   # github.com is the official download host per the vendor homepage
   url "https://github.com/atom/atom/releases/download/v#{version}/atom-mac.zip"
   appcast 'https://github.com/atom/atom/releases.atom',
-          checkpoint: '8e5c44d6f35060f74bf352ef898fea7c394fea554ac1e89cf33bef3cc9624f1f'
+          checkpoint: '29776125d16234655b33d4238ab3f2279f5ae0ebd978afee7aeab4aa62f9d29f'
   name 'Github Atom Beta'
   homepage 'https://atom.io/beta'
   license :mit
```

**Comment by amilajack** [comment]
@vitorgalvao @adidalal Ready to merge

**Comment by vitorgalvao** [comment]
Looks good. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by vitorgalvao** [comment]
There are now conflicts, so will fix in another PR.

**Pull request closed without merging**
