### PR TITLE
Add GitHub Desktop [beta] v0.5.3

### PR DESCRIPTION
**Pull request by danielbayley**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution.

In the future, please do not bundle all the checklist points like you did now. It breaks pattern and makes it harder to check what you’ve done.

Also, Github is touting this beta as the main app, so it belongs in [the main repo](https://github.com/caskroom/homebrew-cask), as [per the documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version) (emphasis added):

> When an App is only available as beta, development, or unstable versions, or in cases **where such a version is the general standard**, then said version can go into the main repo.

Please submit there.

**Comment by yurikoles** [comment]
@danielbayley please use versioned link, it can be obtained by running `wget` against official link to latest beta release.

```
$ wget https://central.github.com/deployments/desktop/desktop/latest/darwin
--2017-05-18 18:32:21--  https://central.github.com/deployments/desktop/desktop/latest/darwin
Resolving central.github.com... 54.82.67.239
Connecting to central.github.com|54.82.67.239|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://desktop.githubusercontent.com/releases/0.5.5-47a3bf36/GitHubDesktop.zip [following]
```

**Comment by danielbayley** [comment]
@vitorgalvao Will do… in that case then, should it be an update to the existing `github-desktop.rb` cask, as opposed to `github-desktop-beta.rb`?

@yurikoles So that would be:
~~~ ruby
version '0.5.5'
url "https://desktop.githubusercontent.com/releases/#{version}-47a3bf36/GitHubDesktop.zip"
~~~
…right?

**Comment by vitorgalvao** [comment]
> in that case then, should it be an update to the existing `github-desktop.rb` cask, as opposed to `github-desktop-beta.rb`?

Yes.

> ~~~ ruby
> version '0.5.5'
> url "https://desktop.githubusercontent.com/releases/#{version}-47a3bf36/GitHubDesktop.zip"
> ~~~

No. It should be

> ~~~ ruby
> version '0.5.5-47a3bf36'
> url "https://desktop.githubusercontent.com/releases/#{version}/GitHubDesktop.zip"
> ~~~

**Comment by danielbayley** [comment]
@vitorgalvao Cool.

Won't the discrepancy between `url 'desktop.githubusercontent.com` and `appcast 'github.com` throw up an error on style checking? Obviously, they are both actually GitHub, so would the "verified" comment above the URL still be necessary here?

**Comment by vitorgalvao** [comment]
> so would the "verified" comment above the URL still be necessary here?

Yes.

**Pull request closed without merging**
