### PR TITLE
Adding Adobe Photoshop CS5

### PR DESCRIPTION
**Pull request by zacs**
Adding automated install (silent) of Photoshop CS5. Linked from
Adobe's official archive download page. No known silent uninstall
for Mac version, so I've left the GUI-based uninstaller commented
out.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Would you mind reviewing, @winkelsdorf?

**Comment by winkelsdorf** [comment]
@vitorgalvao Sure, I'll have a look at and do a test install/uninstall.

**Comment by vitorgalvao** [comment]
Thank you.

**Comment by winkelsdorf** [comment]
You're welcome :) Will take some time though, but should be ready within next 48 hrs.

**Comment by zacs** [comment]
Just a note that since this is app-only (not a collection) there doesn't seem to be a way to uninstall without launching a GUI. I have the GUI launch code in the formula, but it's commented out. Let me know if I should uncomment and squash the commits.

**Comment by winkelsdorf** [comment]
@zacs Thanks for you contribution! From the raw code it looks good. I'll test the Installation later today in a fresh OSX VM for final confirmation.

Regarding the Uninstall: Please leave it as it is now, you are right about that invoking a GUI would violate the Cask rules. I'll have a look on some other casks which require manual Uninstallation, in order to get some ideas how to notify the Users about the requirement for a manual Uninstallation.

**Comment by winkelsdorf** [comment]
@vitorgalvao Casks works fine and can be merged. 

Is there a way to show a text notification when user tries to uninstall (to point them to manual GUI based Uninstallation)? Speaking of a caveat stanza for Uninstall? If so, I'll create a PR to this later.

@zacs: Thanks again for your contribution!

**Comment by vitorgalvao** [comment]
> Is there a way to show a text notification when user tries to uninstall

Nope. There’s an open issue (or comment) about that somewhere, if I recall correctly. That’s still a very underdeveloped area.

**Comment by winkelsdorf** [comment]
Ok, probably best to add it to the Roadmap for the new DSL at some stage. Thanks for merging!

**Pull request merged**
