### PR TITLE
Added Thunderbird galician

### PR DESCRIPTION
**Pull request by alexandregz**

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @alexandregz , sorry for a small delay on your all casks here, could you please rebase latest commits from master and push again to see if it's passing all tests?

(that applies to the rest of your PRs here)

Thanks a lot for your patience and contributions to this project! :wink:

**Comment by alexandregz** [comment]
Ok, no problemo :+1:

**Comment by alexandregz** [comment]
I have sync my fork and then I have made rebase from master with this branch, but finally it appears "Merge branch" when I pull from remote. I don't know if that's correct, so I stop rebase until you can confirm that, plz.

**Comment by radeksimko** [comment]
I cherry-picked your change & merged separately (your contribution is still credited to you as git recognises _committer_ and _author_) and also changed the license to `MPL` as that's afaik [more precise](http://en.wikipedia.org/wiki/Mozilla_Thunderbird).

Thanks.

**Comment by alexandregz** [comment]
thx!

**Pull request closed without merging**
