### PR TITLE
Merge it pls

### PR DESCRIPTION
**Pull request by yurikoles**
sksksksk

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please submit separate pull requests for each cask, as more often than not this type of pull request brings problems with one or more of them, and it halts the inclusion of the other ones.

These commits are non-descriptive and change a bunch of casks at once, making it really confusing. On a first look, at least one problem is apparent. A lot of these have a “no newline at end of file” warning. Those are [actually meaningful](http://unix.stackexchange.com/a/18789).

**Comment by ndr-qef** [comment]
Is this a duplicate of #728? It has already been merged as eb911ea.

**Comment by yurikoles** [comment]
Sorry guys. I was trying to demonstrate power of git and github to my co-worker and I have hit send button by mistake

**Comment by ndr-qef** [comment]
No problem. Closing as duplicate.

**Pull request closed without merging**
