### PR TITLE
Add CCKs (fonts for compatibility with Oracle JDKs) for Zulu casks

### PR DESCRIPTION
**Pull request by dpoggi**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Same question as https://github.com/caskroom/homebrew-versions/pull/4538, do you need both versions?

**Comment by dpoggi** [comment]
The two in this PR are different per major version. `7.0.0.4` gets installed for `zulu7`, `8.0.0.4` gets installed for `zulu8`.

**Comment by commitay** [comment]
Yes, I realise that. I'm asking if _you_ need both versions?

**Comment by dpoggi** [comment]
I do not use `zulu7-cck`. Removing.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4538#issuecomment-333344703

**Pull request closed without merging**
