### PR TITLE
Add MacTeX v20170524 w/o Ghostscript

### PR DESCRIPTION
**Pull request by jlaw**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Ping @vitorgalvao

**Comment by miccal** [comment]
@jlaw why exactly would you want MacTex installed without Ghostscript?

The overwhelming majority of Latex users would want the Ghostscript component installed.

**Comment by jlaw** [comment]
For the users who homebrew Ghostscript or install other software via brew
that requires Ghostscript.

**Comment by miccal** [comment]
@jlaw yes, but I think for the vast majority of users they would prefer the installation of Ghostscript to be handles via the MacTex installer.

**Comment by jlaw** [comment]
Yes I got that, that is why I am submitting the cask formula to
homebrew-versions. Is this the correct tap?

**Comment by commitay** [comment]
> Is this the correct tap?

Per the current [acceptable casks](https://github.com/caskroom/homebrew-versions#acceptable-casks), no.

This should not be in this repo as it is not a dev/beta or legacy cask
____
There has been a [previous request](https://github.com/caskroom/homebrew-cask/issues/15431) for this  that wasn't [possible at the time](https://github.com/Homebrew/brew/pull/1535).

@miccal I'm not familiar with `mactex`, would it work if we modified the main `mactex` cask to not install ghostscript and depend on the `ghostscript` formula? This would allow for other `ghostscript` dependant formula to be installed.

I'll test this and see if it works but I don't use `mactex` or `ghostscript` so I'm not sure if it would be the same functionally?
____
```
brew uses ghostscript --include-build --include-optional
djvu2pdf            gv                  libspectre          ps2eps
epstool             hevea               nuxeo               pstoedit
ettercap            imagemagick         octave              vcs
fig2dev             imagemagick@6       pdf-redact-tools
graphicsmagick      latex2html          pdf2image
```

**Comment by miccal** [comment]
> @miccal Would it work if we modified the main mactex cask to not install ghostscript and depend on the ghostscript formula? This would allow for other ghostscript dependant formula to be installed.

I would not recommend that - Ghostscript is a fairly crucial part of Latex and it is far better to allow MacTex to handle it.

**Comment by commitay** [comment]
@miccal 👍   on the name but I think this should be in the main repo. Similar to `wireshark` and `wireshark-chmodbpf`, this isn't a "version", it just installs different things.

**Comment by miccal** [comment]
@commitay agreed.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38190

**Pull request closed without merging**
