### PR TITLE
Add jce-unlimited-strength-policy8

### PR DESCRIPTION
**Pull request by commitay**
Import from main repo.

https://github.com/caskroom/homebrew-cask/issues/38875

### CODE REVIEW

**Comment by kockas** [comment]
Thanks fot this cask. However it does not work for me.

```
brew cask install jce-unlimited-strength-policy8
Error: Cask 'jce-unlimited-strength-policy8' is unavailable: No Cask with this name exists. 
```

Any idea?

**Comment by commitay** [comment]
Do you have `caskroom/versions` tapped?

**Comment by kockas** [comment]
No, just `caskroom/cask`. After adding `caskroom/versions` it worked. Thanks. :)
Just, it might help to put it also here -> https://caskroom.github.io

**Comment by joelhaasnoot** [comment]
Even after running ```brew tap caskroom/versions``` still can't find this:
```
brew cask install jce-unlimited-strength-policy8
Error: Cask 'jce-unlimited-strength-policy8' is unavailable: No Cask with this name exists.
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4633

**Pull request merged**
