### PR TITLE
Update sequel-pro-nightly to latest

### PR DESCRIPTION
**Pull request by swrobel**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by abhibeckert** [comment]
Instead of parsing the html of our test builds page, you should probably monitor this:

https://sequelpro.com/builds/latest-test-build.xml

That URL is guaranteed to stay the same for the foreseeable future. The page you're hitting now will break when I make some planned changes.

Plus the xml file includes a DSA signature if you'd like to verify that, and it loads faster/consume fewer resources on our server. :-)

**Comment by swrobel** [comment]
@abhibeckert is there a Sparkle appcast for nightlies like this one for regular releases? https://sequelpro.com/appcast/app-releases.xml

**Comment by swrobel** [comment]
@abhibeckert ping!

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4385

**Pull request merged**
