### PR TITLE
Update DBeaver Community to 3.8.4

### PR DESCRIPTION
**Pull request by hugoboos**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It contains [steps that must be followed](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md).

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). If that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [seems to have already implemented it](https://github.com/github/hub/issues/1118), so you may be using an old version).

**Comment by miccal** [comment]
Please ensure you fill in the PR template next time, thanks.

**Comment by hugoboos** [comment]
@vitorgalvao Yes i'm creating PR's with the CLI. Will look into a an updated version. Thanks.

**Comment by vitorgalvao** [comment]
> @vitorgalvao Yes i'm creating PR's with the CLI. Will look into a an updated version. Thanks.

You may wish to try `cask-repair`, that does it for you.

**Pull request merged**
