### PR TITLE
Standardize region and language codes

### PR DESCRIPTION
**Pull request by Zirro**
Updated casks as discussed in #1529.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Changes needed, as per https://github.com/caskroom/homebrew-versions/issues/1529#issuecomment-169001638.

**Comment by Zirro** [comment]
The rule as currently defined will require changes to a much larger number of casks than I am able to go through in my spare time. I am closing this pull request as I can not make the required changes within the foreseeable future.

**Comment by vitorgalvao** [comment]
Why close this? Part of the work was already done, there’s no point in it going to waste.

**Comment by Zirro** [comment]
I was under the impression that anyone could pick up where I left off using my commits, even if I close my pull request. Is this not the case?

**Comment by vitorgalvao** [comment]
You’ve deleted the branch as well, so no.

**Comment by vitorgalvao** [comment]
You’ve delete the branch as well, so it requires a bit more work. But we could’ve just merged it as it was. This isn’t “all or nothing”, they don’t need to be fixed all at once.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in ec93a9eb8df446d43e3496890ada11ff3dcecddf. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by Zirro** [comment]
I see, and will keep that in mind for future situations. Thanks for merging.

**Pull request closed without merging**
