### PR TITLE
Update sourcetree-beta to latest

### PR DESCRIPTION
**Pull request by GregaVrbancic**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but users overwhelmingly prefer versioned casks.

**Comment by GregaVrbancic** [comment]
No problem, that is fine, but you better then remove current sourcetree-beta cask because the download URL does not exist anymore, so the cask is broken. Also there [is no official versioned beta release](https://bitbucket.org/atlassianlabs/sourcetree-betas/downloads?tab=downloads), just the latest one to which I updated this cask.

**Comment by vitorgalvao** [comment]
In that case, that is fine as it is.

**Comment by vitorgalvao** [comment]
Actually, just noticed this is indeed wrong, so I’ll revert it. The link you changed it to goes to the same file as the one that was already present. This has an appcast, it can continue to be versioned.

**Comment by vitorgalvao** [comment]
And the download URL does indeed exist and works fine.

**Comment by GregaVrbancic** [comment]
Great that the url is now working, yesterday certainly was not. Anyway, I'm glad that the cask should work now.

**Pull request merged**
