### PR TITLE
updated airmail-beta (3.0.2.378,258)

### PR DESCRIPTION
**Pull request by victorpopkov**
#### Editing an existing cask

- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by chohner** [comment]
This broke airmail-beta for me:
```
==> Downloading https://rink.hockeyapp.net/api/2/apps/84be85c3331ee1d222fd7f0b59

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'airmail-beta' with message: Download failed: Download failed: https://rink.hockeyapp.net/api/2/apps/84be85c3331ee1d222fd7f0b59e41b04/app_versions/258?format=zip&
```

**Comment by victorpopkov** [comment]
Thank you @chohner for your report. However, there is nothing wrong with the download URL so it shouldn't result in 404 error. You can try again, maybe this was a temporary issue.

On the other hand, there is also a new version available. Done in https://github.com/caskroom/homebrew-versions/pull/2346.

**Comment by chohner** [comment]
Just tried again. Now the download goes through but throws a sha256 mismatch on completion
```Error: sha256 mismatch
Expected: 032da28de8f6fef5ad8ed87291aa412b44f7a073bdeb1a685920c5fc0556ad42
Actual: 2253ba96d279edfd1300e87b35add22c1585c6d802803c911db21c1792a27e29
```

I assume it's working fine for you? I'll wait for the new version to see if the problem persists on my end.

**Comment by victorpopkov** [comment]
I agree, there is a sha256 mismatch now for this version. Double checked on my side. Most likely the vendor has made some changes in the 3.0.2 (378) release as 2 days ago the checksum was different.

I'll merge https://github.com/caskroom/homebrew-versions/pull/2346 as soon as the Travis passes.

**Pull request merged**
