### PR TITLE
clion-eap-bundled-jdk

### PR DESCRIPTION
**Pull request by andystanton**

### CODE REVIEW

**Comment by andystanton** [comment]
Add to #879

**Comment by vitorgalvao** [comment]
Pinging @sebroeder.

**Comment by andystanton** [comment]
@sebroeder I've changed the ```conflicts_with``` stanza and fixed up the commit.

**Comment by andystanton** [comment]
@sebroeder I've changed the ```conflicts_with``` stanza and fixed up the commit.

**Comment by sebroeder** [comment]
Sorry for the delay, :+1: from me. Thanks @andystanton /cc @vitorgalvao

**Pull request merged**
