### PR TITLE
Cleanup localized casks.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by yurikoles** [comment]
shipit!

**Comment by reitermarkus** [comment]
This depends on https://github.com/Homebrew/brew/pull/906, which is still in the works, so this cannot be shipped as of yet.

**Comment by RobberPhex** [comment]
Homebrew/brew#906 was merged, so I think this pr can merge.

**Comment by reitermarkus** [comment]
There is a bug in `brew cask audit`, which would result in this PR going green even if *some* of the languages failed. So this is on hold until https://github.com/Homebrew/brew/pull/1216 is merged and tagged.

**Pull request merged**
