### PR TITLE
Update firefox-beta to 52.0b4

### PR DESCRIPTION
**Pull request by neutric**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
Are you sure `52.0b4` is publicly available? I only see links to `52.0b3`.

**Comment by neutric** [comment]
I thought I checked but it was early in the morning so... ;) It is now though. Will fix the above after some sleep.

**Comment by miccal** [comment]
Restarted the build.

**Comment by neutric** [comment]
Thanks. :) Might very well be that I caught a moment where things where in flux.

**Pull request merged**
