### PR TITLE
Adding cask cornerstone2  v2.7.18

### PR DESCRIPTION
**Pull request by NZRoadKill**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
`cornerstone` was updated to `3` over a year ago. https://github.com/caskroom/homebrew-cask/pull/24154

> https://github.com/caskroom/homebrew-versions#acceptable-casks
> expected to be used by a reasonable number

Not really sure if we should add this if no one has had a need for it previously.

Ping @vitorgalvao

**Comment by vitorgalvao** [comment]
I’m for refusal.

Thank you anyway for the submission, @NZRoadKill, but this particular one might be better suited for a personal tap.

**Comment by NZRoadKill** [comment]
I understand the refusal, but how do you determine demand for a cask? I assume most users that don't find a cask will simply move on to manual install rather than make a request for addition.

**Comment by vitorgalvao** [comment]
> but how do you determine demand for a cask?

It’s subjective. In this case it has been over a year without anyone actually caring for version 2, so I’m confident in saying demand is low.

> I assume most users that don't find a cask will simply move on to manual install rather than make a request for addition.

If a users doesn’t care to the point of not even making a request, that they don’t want it that much in HBC.

**Pull request closed without merging**
