### PR TITLE
Correct download link & update zap paths

### PR DESCRIPTION
**Pull request by andystanton**
Also adhered to rubocop style recommendations.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by vitorgalvao** [comment]
Double quotes are reserved for cases where string interpolation is needed. Please change all of those that don’t need it to single quotes.

If rubocop is letting those pass, it is wrong in this repo.

**Comment by andystanton** [comment]
sorted @vitorgalvao

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
