### PR TITLE
Update slicer-nightly to 4.9.0.26685,727991

### PR DESCRIPTION
**Pull request by fepegar**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
You need to delete the old `cask-repair` branch, the commit in this PR is 20 days old.

**Comment by fepegar** [comment]
Hi @commitay. I'm not sure what you mean by deleting the old `cask-repair` branch. Could you please be more specific? Where should I delete it from?

**Comment by commitay** [comment]
Run `cask-repair --delete-branches`

**Comment by fepegar** [comment]
```
$ cask-repair --delete-branches            
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 3), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/fepegar/homebrew-cask
 * [new branch]          master             -> fepegar/master
 * [new branch]          update-gimp-binary -> fepegar/update-gimp-binary
To https://github.com/fepegar/homebrew-cask
 - [deleted]             cask_repair_update-slicer
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I don't know why I get the error. Anyway, is that enough? Should I open a new PR?

**Pull request closed without merging**
