### PR TITLE
Update IntelliJ IDEA 2017.1 EAP platform to build 171.3019.7

### PR DESCRIPTION
**Pull request by metyl**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by neutric** [comment]
SHA256 for https://download.jetbrains.com/idea/ideaIC-171.3019.7.dmg is def347f3a399284f12c21b11a6eb60b9e348d57ec2db2929f093cf9edcdea5e0

**Comment by vitorgalvao** [comment]
> SHA256 for https://download.jetbrains.com/idea/ideaIC-171.3019.7.dmg is def347f3a399284f12c21b11a6eb60b9e348d57ec2db2929f093cf9edcdea5e0

Confirmed and fixed.

**Comment by metyl** [comment]
@neutric thx for spotting, @vitorgalvao thx for fix, I don't know how I missed it.

**Comment by neutric** [comment]
No problem!

**Pull request merged**
