### PR TITLE
Update rhinoceroswip (5C249w)

### PR DESCRIPTION
**Pull request by cprecioso**
#### Editing an existing cask

- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download rhinoceroswip` is error-free.
- [x] `brew cask style --fix rhinoceroswip` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Shouldn’t this one have `auto_updates true` as well?

**Comment by cprecioso** [comment]
Seems to be disabled for WIP / haven't added it yet / doesn't work on my machine. Also, it says nothing about it in the changelog.

**Comment by adidalal** [comment]
Found the `appcast`: `https://files.mcneel.com/rhino/5.0/mac/5CwipUpdates.xml`

**Comment by cprecioso** [comment]
Done. The zap section is the same as the stable version because they both use the same preferences (source: [`Rhinoceros and RhinoWIP share preferences and a license.`](http://discourse.mcneel.com/t/rhino-for-mac-work-in-progress-rhinowip/28040).

**Pull request merged**
