### PR TITLE
Fix wmail-pre-release app name retargeting

### PR DESCRIPTION
**Pull request by fdrouet**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
[`target:` Should Only Be Used in Select Cases](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases).

This already has a `conflicts_with`, which is the whole point.

**Comment by fdrouet** [comment]
I don't agree with your decision to close the PR because without this change the Cask is not technically able to install because the official app name in the dmg is `WMail.app` not `WMail pre-release.app`. But what I really want to have is the `WMail pre-release.app` app name to simply know that what is installed is the pre-release channel of the application.

For the `conflicts_with` parameter, I defined it because we can't install both casks (wmail and wmail-pre-release) because they will write their data at the same location on the disk.

**Comment by vitorgalvao** [comment]
> But what I really want

And that is your personal desire and we don’t cater to individual user’s desires. Just like *you* want it to have a different name, a different user will want it to have *the original name the developer name gave it*. The latter case always takes precedence.

**Comment by fdrouet** [comment]
Ok so please reopen the PR to let me fix the installation problem ;-)

**Comment by vitorgalvao** [comment]
> Ok so please reopen the PR to let me fix the installation problem ;-)

[Done](https://github.com/caskroom/homebrew-versions/commit/2bd28e20b1f6813258e2805d3590bf45e17c8da0).

**Comment by fdrouet** [comment]
ok got it.

**Pull request closed without merging**
