### PR TITLE
Add Skype 7.59.37 as skype7

### PR DESCRIPTION
**Pull request by lukewang1024**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> https://github.com/caskroom/homebrew-versions#acceptable-casks
> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

**Comment by lukewang1024** [comment]
Thanks for the tip @commitay. However I was wondering if Skype could be categorised as gratis software as it looks like a "commercial" product to me. 

Skype 8.x is an overhaul of the app. My experience is that some features becomes missing in the new version and the CPU usage is much higher than 7.x. Perhaps Microsoft is aware of this, which is why the link to the classic 7.x Skype is provided officially and user cannot find 8.x upgrade from a 7.x app's "Check for Upgrade" feature.

I believe there are users who want to stick with the classic 7.x app until it becomes obsolete or 8.x app matures and having it in versions tap could be handy to them. If you disagrees, I'm fine with hosting it in my own tap. Cheers!

**Comment by commitay** [comment]
Reopened because of multiple requests: https://github.com/caskroom/homebrew-versions/issues/4923, https://github.com/caskroom/homebrew-versions/issues/4695

> expected to be used by a reasonable number of people
___
Missing features would satisfy this requirement:

> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

Ping @vitorgalvao for approval

**Comment by vitorgalvao** [comment]
> I was wondering if Skype could be categorised as gratis software as it looks like a "commercial" product to me.

We have definitions for these terms as we use them in the contest of HBC. “Commercial” means closed-source paid software; “gratis” means closed source free (as in beer) software with no limitations that could be removed by paying (freemium).

**Comment by commitay** [comment]
Thanks for the PR @lukewang1024!

**Pull request merged**
