### PR TITLE
Add vivaldi snapshot 1.0.156.2

### PR DESCRIPTION
**Pull request by Csineneo**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
The version number should be in the name ([example](https://github.com/caskroom/homebrew-versions/blob/master/Casks/vagrant171.rb)). Please [squash your commits](http://davidwalsh.name/squash-commits-git).

But why is this snapshot here? What’s the value in this specific version?

**Comment by Csineneo** [comment]
Like iterm and iterm-beta, google-chrome and google-chrome-beta, vivaldi snapshot is also an unstable version.

**Comment by vitorgalvao** [comment]
Ah, got it, that is fine, then. Can you squash the commits or do you need me to do it?

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in the below referenced pull request. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
