### PR TITLE
Update royal-tsx-beta.rb

### PR DESCRIPTION
**Pull request by Asshad**
Hash update

### CODE REVIEW

**Comment by Asshad** [comment]
Hi Vitor,

Thanks for the update. But it didn't work as freemium. Hmm.

**Comment by adityadalal924** [comment]
Seems Freemium to me
screen shot 2015-10-27 at 11 14 19 am

**Comment by vitorgalvao** [comment]
It isn’t `:freemium`, no, it is actually `:gratis`.

[The business model of the company is irrelevant, what matters is the app itself](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#license-stanza-details).

**Comment by Asshad** [comment]
Hi Vitor,

Could you please enlighten me with those? 
"It isn’t :freemium, no, it is actually :gratis."

I managed to pull and installed but still,:freemium,it's limited to 10 connection only.

Any other way to get that as :gratis ?

**Comment by vitorgalvao** [comment]
> Any other way to get that as :gratis ?

It doesn’t matter. That’s just a reference in the cask, it has no bearing in your use of the app.

**Comment by vitorgalvao** [comment]
Looks like it is `:freemium` indeed. I see now what I missed it that text of theirs. Thought the app without limitation would be a different binary.

**Comment by Asshad** [comment]
Yeah, I guess the app has been patched. That'll only work for beta checksum. 

If you have any workaround, it'd be lovely if you could share with me.

**Comment by vitorgalvao** [comment]
Workaround for what?

**Comment by Asshad** [comment]
The one without limitation(Royal Tsx)

**Comment by adityadalal924** [comment]
You can buy Royal TSX [here](http://www.royalapplications.com/ts/osx/buy)

The `license` stanza refers to the app; `freemium` means that the app has some free features, and you need to pay for the rest. See [here](https://en.wikipedia.org/wiki/Freemium) if you are still confused about this type of business model.

**Comment by Asshad** [comment]
Alritey. Got it. Thanks sir.

**Pull request merged**
