### PR TITLE
Update intellij-idea-ce to 2016.1.1

### PR DESCRIPTION
**Pull request by Jerzerak**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Doesn’t `zap` need to be updated as well?

**Comment by Jerzerak** [comment]
Does it? From what I understand, I thought that JetBrains was going to be incrementing that every major release (so on 2016.2)

**Comment by vitorgalvao** [comment]
> Does it?

I don’t know. I‘m really asking.

**Comment by Jerzerak** [comment]
Yep just triple checked with a fresh install and they all defaulted to 2016.1

**Comment by Jerzerak** [comment]
Wait on a merge though, I am going to change one more thing

**Comment by vitorgalvao** [comment]
In that case, please change occurrences of `2016.1` in `zap` to `#{version.major_minor}`.

**Comment by Jerzerak** [comment]
Done on my end, let me know if anything else needs changing

**Comment by vitorgalvao** [comment]
Should be `#{version.major_minor}` to output `2016.1`. `#{version.major}` outputs `2016`. Is that correct?

**Comment by Jerzerak** [comment]
This is what I get for not sleeping last night...one sec

**Comment by Jerzerak** [comment]
Thanks for being so patient Vítor

**Comment by vitorgalvao** [comment]
No problem. Thank you for being so fast with the changes.

But go rest! Software can wait.

**Pull request merged**
