### PR TITLE
 Update 2 Casks: change to license caveat DSL

### PR DESCRIPTION
**Pull request by commitay**
Need to wait for a new tag before we merge this.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Maybe lose the parentheses, since we don't use parentheses for stanzas either.

**Comment by commitay** [comment]
> Maybe lose the parentheses, since we don't use parentheses for stanzas either.

I don't understand what this means?

**Comment by commitay** [comment]
Okay, I've had another ☕️. If parentheses aren't required (and they aren't) all of our caveats are wrong.

**Comment by vitorgalvao** [comment]
> If parentheses aren't required (and they aren't) all of our caveats are wrong.

Not wrong, but we’re somewhat inconsistent. We always use parenthesis in `depends_on_java`, but never on the other cases (except [one that slipped through](https://github.com/caskroom/homebrew-cask/pull/47286)).

**Pull request merged**
