### PR TITLE
Update intellij-idea-next-*-eap (2016.3 EAP) to build 163.7743.17

### PR DESCRIPTION
**Pull request by metyl**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
`before_comma` is preferred. Also, took the change tom fix `name`.

**Comment by metyl** [comment]
@vitorgalvao maybe we should add **next** in the `name`?

**Comment by vitorgalvao** [comment]
> maybe we should add **next** in the `name`?

Yes, missed that.

**Comment by fanquake** [comment]
Does anything else need doing here?

**Comment by vitorgalvao** [comment]
> Does anything else need doing here?

Adding the **next** in the name. Mind doing that, @metyl?

**Comment by metyl** [comment]
No problem I can add **next** in the name.

**Pull request merged**
