### PR TITLE
Add British English version of Adobe Photoshop

### PR DESCRIPTION
**Pull request by danielbayley**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download adobe-photoshop-cc-gb` is error-free.
- [x] `brew cask style --fix adobe-photoshop-cc-gb` left no offenses.
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-versions/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-versions/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install adobe-photoshop-cc-gb` worked successfully.
- [x] `brew cask uninstall adobe-photoshop-cc-gb` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@vitorgalvao, I know [we've had this discussion before](https://github.com/caskroom/homebrew-cask/pull/14367/files), but I would still argue that the default casks should install the localized version matching the system language as this is also what happens when you manually install it, and only have `-en` casks for people that, as you said

> prefer their system in one language (many times their native one) and their apps in another (mostly english)

**Comment by vitorgalvao** [comment]
@reitermarkus But can we be consistent with that rule across casks? Because I think we cannot, and that seems like a bad experience to me (users will be surprised when some localize and the others not, even the ones that should).

I wouldn’t oppose at all a solution like `--localized`, as in `brew cask install --localized adobe-photoshop` (naturally, `--localized` could also be given as a `HOMEBREW_CASK_OPTS` option). That would also standardise our naming scheme for languages (we’d use the exact same as macOS).

On a tangential note, I’d prefer for UK English to be the default, but US English makes more sense as the default for most apps.

**Comment by reitermarkus** [comment]
While the idea of a `--localized` option sounds nice, it would really only be usable for edge cases, and then you would still have to translate the specified language slug into the correct format, like here with `-` and `_`.

For `.app` casks and any other *native* applications, the translations are already bundled.

> But can we be consistent with that rule across casks? Because I think we cannot

I don't see why not, also I don't know if there even are other casks than the Adobe ones that are multilingual but aren't native apps.

**Comment by danielbayley** [comment]
> I don't know if there even are other casks than the Adobe ones that are multilingual but aren't native apps.

Trust Adobe to screw it up…

**Comment by reitermarkus** [comment]
Ok, so there are Firefox and Thunderbird, which for some reason use language packs instead of bundling translations natively, other than that, I don't think there are any.

**Comment by vitorgalvao** [comment]
@reitermarkus Open an discussion issue on the main repo. If there are no objections, I’m fine with changing the rule.

**Comment by vitorgalvao** [comment]
Closing, since merging languages is in progress and seems to have no objections.

**Pull request closed without merging**
