### PR TITLE
Update intellij-idea-eap to 2017.1,171.3780.15

### PR DESCRIPTION
**Pull request by gobinathm**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by arvindsv** [comment]
As I mentioned in #30873, the new URL is: https://download-cf.jetbrains.com/idea/ideaIU-171.3780.15.dmg

So, [this line](https://github.com/gobinathm/homebrew-versions/blob/51d20390dfc96be963b731836d0d9a9b47543fe8/Casks/intellij-idea-eap.rb#L5) has to change.

**Comment by arvindsv** [comment]
Hmm, there seems to be something wrong, still. I don't know if it's only with me.

```
$ brew cask install intellij-idea-eap
==> Downloading https://download-cf.jetbrains.com/idea/ideaIU-171.3780.15.dmg
Already downloaded: /Users/myuser/Library/Caches/Homebrew/Cask/intellij-idea-eap--2017.1,171.3780.15.dmg
==> Verifying checksum for Cask intellij-idea-eap
Error: It seems the App source '/usr/local/Caskroom/intellij-idea-eap/2017.1,171.3780.15/IntelliJ IDEA.app' is not there.
Error: nothing to install

$ ls /usr/local/Caskroom/intellij*
ls: cannot access '/usr/local/Caskroom/intellij*': No such file or directory
```

I took a look at [this](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_fix.md) to see if it's an issue that's documented. It seems to suggest that there should be an archive. But, there's only the dmg, as far as I can see.

If you'd like me to open another issue, let me know. Thank you!

**Comment by gobinathm** [comment]
@arvindsv  i have submitted another pull which corrects this problem. Hence no need to raise new issue. you can test it by 

```
brew cask install https://raw.githubusercontent.com/gobinathm/homebrew-versions/3e5a28d7c1f77946ea175061b32417e30379f320/Casks/intellij-idea-eap.rb
```

Ref. #3447  PR that correct problem mentioned

**Comment by jcrben** [comment]
The name right now, `intellij-idea20161`,  is weird and inconsistent: https://github.com/caskroom/homebrew-versions/blob/master/Casks/intellij-idea20161.rb

Think I'll make a PR...

**Comment by commitay** [comment]
@jcrben All EAP versions were removed: https://github.com/caskroom/homebrew-versions/pull/3683

The naming of `intellij-idea20161` is correct for a legacy version.

**Pull request merged**
