### PR TITLE
Update visual-studio-code-insiders to 1.23.0,4971d889244a2e569ff03b7211c50e2a159e6e71

### PR DESCRIPTION
**Pull request by coreygo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by coreygo** [comment]
Strange, looks like my SHA256 isn't right, as calculated by cask-repair:

```
$ openssl sha -sha256 visual-studio-code-insiders--1.23.0,95101bf3f6d00105621cdddb639ea62b95ea2468.zip
a4335f2b8680c84c37f6b108bf453451b6f535b3fa1e775da15ed6956d058762
$ shasum -a 256 visual-studio-code-insiders--1.23.0,95101bf3f6d00105621cdddb639ea62b95ea2468.zip | awk '{ print $1 }'
a4335f2b8680c84c37f6b108bf453451b6f535b3fa1e775da15ed6956d058762
$ shasum -v
5.96
$ which shasum
/usr/local/bin/shasum
```

While the appcast url confirms with Travis…
https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION

`"sha256hash":"ca47a2626eb2d017600a3d06b66c80d333b6c7d815a26c5b7defb315c9252194"`

**Comment by victorpopkov** [comment]
Yes, definitely something strange here. Have checked multiple times and I also get the checksum:
```
a4335f2b8680c84c37f6b108bf453451b6f535b3fa1e775da15ed6956d058762
``` 
By running `cask-repair`, `openssl sha -sha256` and `shasum -a 256`.

**Comment by coreygo** [comment]
Thanks. Glad it's _not me_. Thinking Microsoft's SHA256 is wrong or their system is out of sync.

**Comment by coreygo** [comment]
Opened an issue with Microsoft: https://github.com/Microsoft/vscode/issues/47446

**Comment by coreygo** [comment]
Microsoft pushed an update, [confirmed](https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION) the SHA256 matches now.

**Pull request merged**
