### PR TITLE
Upgrade PhpStorm EAP to 141.1619

### PR DESCRIPTION
**Pull request by bchatard**
Hello,

I try to follow guideline from #879. Let me know if some parts are missing or if there are some mistakes.

Hope this help

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Pinging @sebroeder.

**Comment by fanquake** [comment]
Needs a rebase after #1080

**Comment by bchatard** [comment]
@fanquake done

**Comment by bchatard** [comment]
Jetbrains release a new EAP, so I create a new PR (#1088). This one can be cancelled.

**Pull request closed without merging**
