### PR TITLE
Adding Chirp Daily Builds

### PR DESCRIPTION
**Pull request by mannkind**
In case anyone wants the daily build of chirp. Sadly the filename is never the same so I had to find it within the latest SHA1SUM file.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Automated solutions like this [have been tried](https://github.com/caskroom/homebrew-versions/pull/293#issuecomment-46122949). However, they were removed due to [technical reasons](https://github.com/caskroom/homebrew-versions/pull/293#issuecomment-48755213). Not sure how your solution would be or not affected by that, so I’ll leave this one to @rolandwalker.

**Comment by mannkind** [comment]
No problem. Chirp (esp. the latest build version) is probably not used by too many people anyway; I just found it useful and thought I might share.

**Comment by vitorgalvao** [comment]
I’d still like to keep it open until @rolandwalker takes a loo. It’s a good contribution, and since I’m not sure this would suffer from the same problem as the other ones and he likely does, if it works it’d be something to consider for other casks.

**Comment by rolandwalker** [comment]
Hi!

Yes this is a problem, arguably because of an architectural failing on our part.  Many operations cause all Casks to be loaded, *ie* fully evaluated.  Thus the HTTP connection here is made when operating on a different Cask.  This will slow things down and sometimes cause wedges.

We are moving towards fixing the architecture, at least for some cases.

I dearly love a hack, and thus want to include this gem, but sadly we cannot handle it.

**Comment by vitorgalvao** [comment]
Closing, then. I’m guessing we won’t forget about adding these when time comes.

**Pull request closed without merging**
