### PR TITLE
appcode-eap-custom-jdk

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by yurikoles** [comment]
fix for #879

**Comment by yurikoles** [comment]
And why it's not merged?

**Comment by vitorgalvao** [comment]
@sebroeder Is this in line with the unification you’re working on?

**Comment by sebroeder** [comment]
@vitorgalvao this cask as well as the `appcode-eap` cask are very rough (they even have the version number hard-coded in the download url). I am working on them now.

**Comment by vitorgalvao** [comment]
Done in #1070 (thank you anyway, @yurikoles, but @sebroeder is working hard to fix these all).

**Pull request closed without merging**
