### PR TITLE
Thebrain9

### PR DESCRIPTION
**Pull request by enogrob**
#### Editing an existing cask

- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download thebrain9` is error-free.
- [x] `brew cask style --fix thebrain9` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
This needs a rebase.

**Comment by enogrob** [comment]
...alright, what does it mean? is there any instruction which I can follow?

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in a8619c28e1c952bb11ffaf63cf3cdd6d1c5d930b. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by jawshooah** [comment]
For next time: [`git rebase`](https://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)

**Pull request closed without merging**
