### PR TITLE
Add OmniGraffle 5 Standard cask

### PR DESCRIPTION
**Pull request by benw13**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Should be just `omnigraffle5`, as per the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md).

**Comment by benw13** [comment]
@vitorgalvao fixed

**Comment by vitorgalvao** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by benw13** [comment]
@vitorgalvao squashed

**Pull request merged**
