### PR TITLE
java-beta

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by jawshooah** [comment]
Pinging @radeksimko.

**Comment by vitorgalvao** [comment]
I assigned @radeksimko to this at the time because he worked more on the java-related casks, but you should feel free to take a look (and/or merge) if you’re so inclined, @jawshooah.

**Comment by radeksimko** [comment]
Hi all,
sorry for the silence here, I was and still am quite busy contributing to [`hashicorp/terraform`](https://github.com/hashicorp/terraform/commits?author=radeksimko) and I may not have enough time to look at this in the nearest future, so I'll just leave a few comments/hints/suggestions here.

Since this is a `versions` repo, I treat that as lower prio in terms of stability, but at some point in the future this java version may reach the main repo. This new java cask **significantly** changes the way we install java. It may be necessary (i.e. I'm not saying it's wrong), but it's important to make sure that (ideally all, but at least majority) java-related casks work out of the box with that setup, because that's the current situation and we don't want to break things.

Here's an exhaustive list of casks you may want to test:
https://github.com/caskroom/homebrew-cask/issues/4885

**Comment by fanquake** [comment]
There's a newer beta version available [Java beta 1.8.0_60_25](http://download.java.net/jdk8u60/archive/b25/binaries/jdk-8u60-ea-bin-b25-macosx-x86_64-21_jul_2015.dmg?q=download/jdk8u60/archive/b25/binaries/jdk-8u60-ea-bin-b25-macosx-x86_64-21_jul_2015.dmg)

**Comment by yurikoles** [comment]
@radeksimko I have created this cask before caskroom/homebrew-cask@71560a810b90d6696d5bb9261a7967fc3bb941ae so I have made version handling by myself.
Now I have updated it accordingly to latest java cask. I have also bumped build number. I use plain-text link because `#{version}` doesn't make sense due to test builds file name conventions, e.g. it includes date of build.

**Comment by yurikoles** [comment]
rebased

**Comment by yurikoles** [comment]
Rebase && up.

@vitorgalvao, the cask is mostly same as current java cask except download url, which is raw, because they are custom for each build.

**Comment by vitorgalvao** [comment]
The current java cask is broken, so if this is the same, it’ll be broken as well. There is a PR currently being made to fix it (in the main repo. Since I’m on a phone, cannot easily link you).

**Comment by bdhess** [comment]
The thread is caskroom/homebrew-cask#13941

In addition to @vitorgalvao's notes, I would recommend using the java7 cask as the baseline for a Java beta cask.  The regular Java cask (i.e. latest stable) has a more invasive uninstall procedure.  As currently proposed, an uninstall of this Java beta cask on a system that also has the Java cask installed would leave the system in an undesirable state (no prefpane, applet support removed).

**Comment by fanquake** [comment]
@bdhess Does this need the fixes from https://github.com/caskroom/homebrew-cask/pull/14233 ? I'd like to either get this fixed and merged, or close it until we figure out what to do.

**Comment by vitorgalvao** [comment]
Agreed with @fanquake. If you want to take a crack at it, @bdhess, feel free to open a new PR and we’ll merge that one.

**Comment by bdhess** [comment]
At this point 1.8.0_66 is a final release and is a part of homebrew-cask (b78fb320fc303fc503386aa6fac47fdd105ecbfb).  Suggest closing this PR.

**Comment by yurikoles** [comment]
@bdhess this PR is from times of 1.8.0_60.

**Comment by yurikoles** [comment]
@adityadalal924 please reopen, I will update it later today.

**Comment by bdhess** [comment]
Yes I suppose this could be updated for 8u72-- however, my previous point remains, that the `java7` cask should be the baseline for this one rather than `java`.  An uninstall of `java-beta` shouldn't remove the working prefpane, web plugin, etc from the mainline `java` cask.

**Comment by fanquake** [comment]
Closing, superseded by #1425

**Pull request closed without merging**
