### PR TITLE
Add slack beta

### PR DESCRIPTION
**Pull request by mwarkentin**
### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [ ] The commit message includes the cask’s name and version.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [ ] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-versions/pulls) for the same cask.
- [ ] Checked there are no closed [issues](https://github.com/caskroom/homebrew-versions/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by penman** [comment]
I was just about to submit a Slack beta cask (you beat me by six minutes). There's no need for my PR now, but here are some things from my implementation that might be useful.

- Versioned URL downloads are available:

    ```ruby
    "https://slack-ssb-updates.global.ssl.fastly.net/mac_external_beta/Slack-#{version}-macOS.zip"
   ```
- There's `license`, `uninstall`, and `zap` data in the main [`slack`](https://github.com/caskroom/homebrew-cask/blob/064c2350174d42e3f4f6b317efe69075c2008332/Casks/slack.rb) cask that might be useful here.

**Comment by mwarkentin** [comment]
@penman I haven't tested this at all yet, and won't for a little while. If you had your own more robust version, feel free to submit it and I can close this.

Are versioned casks generally preferred?

**Comment by vitorgalvao** [comment]
> Are versioned casks generally preferred?

Yes.

**Comment by penman** [comment]
@mwarkentin I've submitted mine as #2578. :)

**Comment by mwarkentin** [comment]
Replaced by #2578.

**Pull request closed without merging**
