### PR TITLE
Update palemoon to 27.7.0

### PR DESCRIPTION
**Pull request by wickedsp1d3r**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
Now this is called `newmoon`, whats the difference between this Cask and [`newmoon`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/newmoon.rb) in the main repo?

**Comment by MindTooth** [comment]
Seems to just be a temporary namechange: https://forum.palemoon.org/viewtopic.php?p=132474#p132474

**Comment by commitay** [comment]
Thanks @MindTooth!

**Comment by vitorgalvao** [comment]
Verified Locally.

**Pull request merged**
