### PR TITLE
Remove VOX Legacy cask

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by adityadalal924** [comment]
I see old versions at http://coppertino.com/old-versions, but the cask would need to be renamed to stay within our naming. (legacy isn't a version name)

**Comment by vitorgalvao** [comment]
I was under the impression vox was gratis, though, so it would fit into the rules of removal.

However, from [the main cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vox.rb), it seems like it is freemium after all. I don’t see how on first glance though. Does anyone know if it is indeed freemium?

**Comment by adityadalal924** [comment]
Yeah, I've used it. They added in premium features with the newer versions (radio and some sort of cloud storage service), and also changed the interface, so many people like the old simple, free one.

This cask is probably okay to stay, but should be renamed, as -legacy is quite ambiguous.

**Comment by vitorgalvao** [comment]
Yes, it should stay.

> so many people like the old simple, free one.

So this one in particular should be changed to `:gratis`, then, right?

> but should be renamed

The rule is to use the major version, so should be `vox0`. Looks a bit weird, but it’s accurate.

**Comment by adityadalal924** [comment]
Changes made in https://github.com/caskroom/homebrew-versions/pull/1477

**Pull request closed without merging**
