### PR TITLE
Add Things 2.8.14

### PR DESCRIPTION
**Pull request by linssen**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll refuse this cask. This repo has [stricter acceptance rules](https://github.com/caskroom/homebrew-versions#acceptable-casks) (emphasis added):

> `caskroom/versions` is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be **expected to be used by a reasonable number of people** and supported by contributors long-term.

Considering Things 3 has been released a year ago and there’s been no interest in Things 2 so far, I’d say there’s not a reasonable amount of interest.

As per the instructions, if you want this as a cask, you may create your own tap.

**Comment by linssen** [comment]
Fair enough. Out of interest, how is the 'reasonable number of people' quantified? By PR / issue? Seemed to me the legacy version of Things was a warranted addition since they moved to the App Store, and original licenses are still valid.

**Comment by vitorgalvao** [comment]
> how is the 'reasonable number of people' quantified?

It’s subjective. If it had been added shortly after version 3 was released, we’d have accepted it then.

> Seemed to me the legacy version of Things was a warranted addition

Agreed, if people wanted a cask for it. But so far we had a single PR for it in a year (yours), so clearly our users aren’t really missing it.

**Comment by linssen** [comment]
Understood. Cheers, @vitorgalvao.

**Pull request closed without merging**
