### PR TITLE
Update and rename firefoxdeveloperedition.rb to firefox-dev.rb

### PR DESCRIPTION
**Pull request by miccal**
Renamed for consistency.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Same. Token reference.

**Comment by miccal** [comment]
Apologies, I see what you mean now.

**Comment by miccal** [comment]
Sorry about that @vitorgalvao I was going through the list of Cask filenames for consistency, and did not even think of actually looking at the `artifact`. Silly error on my part.

**Comment by vitorgalvao** [comment]
All good!

**Pull request closed without merging**
