### PR TITLE
Add GPG Tools Yosemite Beta

### PR DESCRIPTION
**Pull request by jalaziz**

### CODE REVIEW

**Comment by niksy** [comment]
Any progress on this?

**Comment by nicolas-brousse** [comment]
I created the PR #669 who duplicate this one. But it use the beta 4 of GPGTools.
I've test it and it works fine on my computer but the travis ci build has errors. And I don't understand what is wrong on testing.

**Comment by vitorgalvao** [comment]
@nicolas-brousse There’s a problem with Travis on this repo, currently. Correct casks are being flagged as failing.

**Comment by nicolas-brousse** [comment]
@vitorgalvao thanks for the precision.

**Comment by rolandwalker** [comment]
Sorry all, I'm assigned to this issue, and haven't forgotten, but am moving slowly.

**Comment by ndr-qef** [comment]
Superseded by https://github.com/caskroom/homebrew-cask/pull/9406. Thanks to everyone who reported on the issue, and sorry for the long wait.

**Pull request closed without merging**
