### PR TITLE
LibreOffice 5.2 alpha1

### PR DESCRIPTION
**Pull request by yurikoles**
Should I submit it under different name?

### CODE REVIEW

**Comment by fanquake** [comment]
Maybe we can rename it to libreoffice-dev so it can include alpha & beta versions?

**Comment by yurikoles** [comment]
@fanquake so let use -dev for beta and alpha and -rc for corresponding releases.

**Comment by fanquake** [comment]
Are you also changing the actual cask name to libreoffice-dev ? I think we could use it for alpha, beta and rc.

**Comment by yurikoles** [comment]
up & rebase

**Pull request merged**
