### PR TITLE
Update libreofficedev to 6.0.4.1

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Is this an update to the stable version?

**Comment by gtmgianni** [comment]
@vitorgalvao No, the current stable release is `6.0.3`.

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/libreofficedev/6.0.4.1/LibreOfficeDev.app' is not there.

**Comment by gtmgianni** [comment]
@vitorgalvao Just wondering, why is TravisBuddy not enabled for this repository?

**Comment by commitay** [comment]
This is now a duplicate of [libreoffice-rc](https://github.com/caskroom/homebrew-versions/blob/master/Casks/libreoffice-rc.rb)

**Comment by yurikoles** [comment]
@commitay don't need to remove it, since `libreofficedev != libreoffice-rc`, when there will be new alpha or beta we will update it.

**Comment by commitay** [comment]
Closing for now, we'll see if upstream publishes a new release sometime in the next couple of months.

Thanks for the PR nonetheless @gtmgianni!

**Pull request closed without merging**
