### PR TITLE
Add Vagrant v1.8 (lastest minor revision: v1.8.7)

### PR DESCRIPTION
**Pull request by jayusa123**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-versions/pulls
[closed issues]: https://github.com/caskroom/homebrew-versions/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by vitorgalvao** [comment]
[Why](https://github.com/caskroom/homebrew-versions#acceptable-casks)?

**Comment by jayusa123** [comment]
Breaking change(s) introduced in v1.9. In my internet travels today I came across others with a need to downgrade to v1.8 as well. I've already shoehorned v1.8.7 on my machine, but I thought I'd leave behind a paved path for others.

**Comment by miccal** [comment]
> Breaking change(s) introduced in v1.9. In my internet travels today I came across others with a need to downgrade to v1.8 as well. I've already shoehorned v1.8.7 on my machine, but I thought I'd leave behind a paved path for others.

@jayusa123 can you provide some links about this?

**Comment by miccal** [comment]
Closing due to lack of response.

**Pull request closed without merging**
