### PR TITLE
Add VirtualBox 4.3.26-98988 as virtualbox432698988

### PR DESCRIPTION
**Pull request by JohnLZeller**
I'd like to add VirtualBox 4.3.26-98988 to the alternate versions set. Retrieved sha256 hash by running shasum -a 256 VirtualBox-4.3.26-98988-OSX.dmg

### CODE REVIEW

**Comment by JohnLZeller** [comment]
When will this become usable?

**Comment by vitorgalvao** [comment]
It already is.

**Comment by JohnLZeller** [comment]
Oh, hmmm. I guess I must be caching or something. I don't see it popping up for me. Thanks!

**Comment by vitorgalvao** [comment]
You need to `brew update`.

**Comment by JohnLZeller** [comment]
Ah, derp. New to brew :) Thanks!

**Pull request merged**
