### PR TITLE
Update IntelliJ IDEA CE to EAP 15; version 142.2491.4.

### PR DESCRIPTION
**Pull request by narbsy**

### CODE REVIEW

**Comment by narbsy** [comment]
@sebroeder can you approve + merge this? thanks!

**Comment by sebroeder** [comment]
@narbsy Looks great, thanks. :+1: (sorry for the late reply). I have no commit rights, so we have to wait for one of the great core members to merge this in.

**Comment by vitorgalvao** [comment]
Thank you for the review, @sebroeder.

**Comment by narbsy** [comment]
@sebroeder -- no worries, and thanks for the review!
@vitorgalvao -- thanks for the merge :)

**Pull request merged**
