### PR TITLE
[Hold until caskroom/homebrew-cask#5248] keyremap4macbook: all versions before rename

### PR DESCRIPTION
**Pull request by vitorgalvao**
Refs #586.

Hold until caskroom/homebrew-cask#5248 is fixed.

### CODE REVIEW

**Comment by fanquake** [comment]
@vitorgalvao What's the status of this? Looks like caskroom/homebrew-cask#7815 has been closed and somewhat fixed by caskroom/homebrew-cask#7935. Are we still waiting on caskroom/homebrew-cask#5248 ?

**Comment by vitorgalvao** [comment]
Yes. Without it, the cask still does not pass audit.

**Comment by adityadalal924** [comment]
@vitorgalvao This looks like an old PR (with a lot of unrelated commits).
Safe to close?

**Comment by vitorgalvao** [comment]
Clearly it got screwed at some point, so yes.

**Pull request closed without merging**
