### PR TITLE
Add Vagrant v1.7.4

### PR DESCRIPTION
**Pull request by mariusbutuc**
Add cask for Vagrant 1.7.4

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but this goes against our [acceptable casks policy](https://github.com/caskroom/homebrew-cask/blob/d72198ee07c4226d9e06dbe3b0d406ad491a5f0d/USAGE.md#tab-completion).

> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

**Comment by adityadalal924** [comment]
@mariusbutuc If you need if for your organization, it's really easy to [host your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md)

**Comment by mariusbutuc** [comment]
Hey @vitorgalvao and @adityadalal924, thanks a lot for your feedback!

Went again over the [criteria for acceptable formulae](https://github.com/Homebrew/homebrew-versions#acceptable-formulae), and it's difficult to evaluate this part:
> […] casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

How does one confirm that a specific version is used by a reasonable number of people? 

On top of that, given the existence of individual formulae for [1.7.1](https://github.com/caskroom/homebrew-versions/blob/master/Casks/vagrant171.rb), [1.7.2](https://github.com/caskroom/homebrew-versions/blob/master/Casks/vagrant172.rb), and [1.7.3](https://github.com/caskroom/homebrew-versions/blob/master/Casks/vagrant173.rb) could you please help me understand better how these criteria are applied?

**Comment by vitorgalvao** [comment]
> How does one confirm that a specific version is used by a reasonable number of people?

The answer is partially in my previous quote:

> a clear demonstrable need for them.

The rules isn’t about (quoting again from your post “used by a reasonable number of people”, but “used by a reasonable number of people **and** be supported long term”. There’s no reason to believe there’s any long-term (or even mid-term) gain in having that old version of Vagrant around).

> On top of that, given the existence of individual formulae for 1.7.1, 1.7.2, and 1.7.3 could you please help me understand better how these criteria are applied?

Those were simply not removed yet (the rules are recent, so not everything was rectified yet).

**Comment by adityadalal924** [comment]
@mariusbutuc See the prior discussion at https://github.com/caskroom/homebrew-versions/issues/1450

Re: the earlier version; I beilieve we kept them under the clause
> Legacy versions of gratis or open-source software that were accepted should be removed after one year.

**Comment by vitorgalvao** [comment]
> Re: the earlier version; I beilieve we kept them under the clause

We haven’t clarified that in the discussion, I realise. I think we should start by getting them all out (as you recently did to virtualbox) and start counting from there.

**Comment by mariusbutuc** [comment]
Thanks a lot guys, makes total sense now!
Will keep these guidelines in mind for future contributions. :v:

**Comment by adityadalal924** [comment]
Sure. Also FYI if you do end up making a personal tap for that specific version, you can get official vendor binaries from https://releases.hashicorp.com/vagrant/, no need to use that bintray download.

(Another reason why we need to clean up this repo - it's really hard to maintain)

**Pull request closed without merging**
